# Generated resource file - auto-generated from resources.qrc
# This file would normally be generated by running:
# pyrcc5 resources.qrc -o resources.py

# For now, we'll create a simple version that loads the icon
import os
from pathlib import Path

def get_icon_path():
    """Get the path to the plugin icon"""
    plugin_dir = Path(__file__).parent
    return str(plugin_dir / "icons" / "main.ico")
